-- Insert Agastya Sales vendor with complete realistic data (fixed JSONB casting)
INSERT INTO public.suppliers (
    supplier_code,
    supplier_name,
    supplier_type,
    category,
    contact_person,
    email,
    phone,
    address,
    tax_details,
    bank_details,
    payment_terms,
    credit_limit,
    minimum_order_value,
    lead_time_days,
    material_categories,
    certifications,
    performance_rating,
    is_active,
    is_approved,
    created_at,
    updated_at
) VALUES (
    generate_supplier_code(),
    'Agastya Sales',
    'DISTRIBUTOR',
    'STANDARD',
    'Rajendra Agastya',
    'rajendra@agastyasales.com',
    '+91-9876543214',
    '{"street": "Plot 42, Industrial Area Phase II", "city": "Chandigarh", "state": "Punjab", "postal_code": "160002", "country": "India"}'::jsonb,
    '{"gst_number": "03ABCDE1234F1Z5", "pan_number": "ABCDE1234F", "registration_type": "Regular"}'::jsonb,
    '{"bank_name": "State Bank of India", "account_number": "123456789012", "ifsc_code": "SBIN0001234", "account_type": "Current", "beneficiary_name": "Agastya Sales"}'::jsonb,
    'NET_30',
    500000,
    25000,
    12,
    '["BOPP", "ADHESIVES"]'::jsonb,
    '["ISO_9001"]'::jsonb,
    70,
    true,
    false,
    now(),
    now()
);